// Auto-generated by TanStack Router — do not edit
// Regenerate with: npm run dev or npm run build

import { rootRoute } from "@tanstack/react-router"

// This file will be regenerated by the router plugin.
// Run `npm run dev` or `npm run build` to generate the complete route tree.

export const routeTree = rootRoute
