/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as DashboardRouteRouteImport } from './routes/dashboard/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as DashboardSettingsRouteRouteImport } from './routes/dashboard/settings/route'
import { Route as DashboardRenderRouteRouteImport } from './routes/dashboard/render/route'
import { Route as DashboardProjetsRouteRouteImport } from './routes/dashboard/projets/route'
import { Route as DashboardAgentRouteRouteImport } from './routes/dashboard/agent/route'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRouteRoute = DashboardRouteRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardSettingsRouteRoute = DashboardSettingsRouteRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardRenderRouteRoute = DashboardRenderRouteRouteImport.update({
  id: '/render',
  path: '/render',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardProjetsRouteRoute = DashboardProjetsRouteRouteImport.update({
  id: '/projets',
  path: '/projets',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardAgentRouteRoute = DashboardAgentRouteRouteImport.update({
  id: '/agent',
  path: '/agent',
  getParentRoute: () => DashboardRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/dashboard/agent': typeof DashboardAgentRouteRoute
  '/dashboard/projets': typeof DashboardProjetsRouteRoute
  '/dashboard/render': typeof DashboardRenderRouteRoute
  '/dashboard/settings': typeof DashboardSettingsRouteRoute
  '/dashboard/': typeof DashboardIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard/agent': typeof DashboardAgentRouteRoute
  '/dashboard/projets': typeof DashboardProjetsRouteRoute
  '/dashboard/render': typeof DashboardRenderRouteRoute
  '/dashboard/settings': typeof DashboardSettingsRouteRoute
  '/dashboard': typeof DashboardIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/dashboard/agent': typeof DashboardAgentRouteRoute
  '/dashboard/projets': typeof DashboardProjetsRouteRoute
  '/dashboard/render': typeof DashboardRenderRouteRoute
  '/dashboard/settings': typeof DashboardSettingsRouteRoute
  '/dashboard/': typeof DashboardIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/auth'
    | '/dashboard/agent'
    | '/dashboard/projets'
    | '/dashboard/render'
    | '/dashboard/settings'
    | '/dashboard/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/dashboard/agent'
    | '/dashboard/projets'
    | '/dashboard/render'
    | '/dashboard/settings'
    | '/dashboard'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/auth'
    | '/dashboard/agent'
    | '/dashboard/projets'
    | '/dashboard/render'
    | '/dashboard/settings'
    | '/dashboard/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRouteRoute: typeof DashboardRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/settings': {
      id: '/dashboard/settings'
      path: '/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof DashboardSettingsRouteRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/render': {
      id: '/dashboard/render'
      path: '/render'
      fullPath: '/dashboard/render'
      preLoaderRoute: typeof DashboardRenderRouteRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/projets': {
      id: '/dashboard/projets'
      path: '/projets'
      fullPath: '/dashboard/projets'
      preLoaderRoute: typeof DashboardProjetsRouteRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/agent': {
      id: '/dashboard/agent'
      path: '/agent'
      fullPath: '/dashboard/agent'
      preLoaderRoute: typeof DashboardAgentRouteRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
  }
}

interface DashboardRouteRouteChildren {
  DashboardAgentRouteRoute: typeof DashboardAgentRouteRoute
  DashboardProjetsRouteRoute: typeof DashboardProjetsRouteRoute
  DashboardRenderRouteRoute: typeof DashboardRenderRouteRoute
  DashboardSettingsRouteRoute: typeof DashboardSettingsRouteRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteRouteChildren: DashboardRouteRouteChildren = {
  DashboardAgentRouteRoute: DashboardAgentRouteRoute,
  DashboardProjetsRouteRoute: DashboardProjetsRouteRoute,
  DashboardRenderRouteRoute: DashboardRenderRouteRoute,
  DashboardSettingsRouteRoute: DashboardSettingsRouteRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteRouteWithChildren = DashboardRouteRoute._addFileChildren(
  DashboardRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRouteRoute: DashboardRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
